### ISSUE TITLE
【制作課題】 5年後のプロフィールサイトを作ってください

### ISSUE THREAD

**Issue by uchidacode** [torobi/201907-256times#1]
今回の「制作課題」では「5年後のプロフィールサイト」を作ってみてください。

256timesに合格したあかつきには、このサイトを使って他のメンバーに自己紹介をしてもらう予定なので、そのつもりで作り込んでください。

### 盛り込むべき内容

- 5年後にどのような活動をしていたいか？がわかること
- この人と友達になりたい！もっとこの人のことを知りたい！と思わせること

### 技術的な仕様

制作するにあたっては以下の仕様をご確認ください。

- HTML/CSSのみで記述してください。
- 画像はどこかにアップロードしたものを使うか、フリー素材を使ってください。
  - 画像のアップロード方法は7/8に送信したメールを参照してください。
- 1ページのみでシンプルに作ってください。
- JavaScriptは使わないでください。
- スマホから見て違和感のないレイアウトにしましょう。
- 適切なタグでマークアップしてください。
  - 安易にすべてを`div`でマークアップしないでください。

### 提出について

以下のことができた時点でレビューを受けるようにしてください。

- だいたいの盛り込みたい内容を文章で書けたとき
  - → **Issueにマークダウン形式でコメントしてください。**
- だいたいのレイアウトが決まったとき
  - → **手描きでいいのでイメージ図をコメントにアップしてください。**
- HTML/CSSでのマークアップが終わったとき
  - → **上述のプレイグラウンドを編集して保存後、URLをコメントにアップしてください。**

### 雛形となるプレイグラウンド

マークアップまで進んだら、以下のプレイグラウンドを複製して編集して下さい。
`title`タグも含め、自由に編集していただいてかまいません。

・課題用プレイグラウンド
https://dotinstall.com/pg/taguchi/81woza920j9liex/3

---

課題は以上です。なにかわからないことがあればこのIssueのコメントまでどうぞ！
時間も限られているのでシンプルなサイトが良いと思います。がんばってみてください！

**Comment by torobi** [comment]
以下に盛り込みたい内容をまとめました。
レビューよろしくお願いいたします！

### 内容
- プロダクトデザイナー・ディベロッパー・店主
- 「生活を楽しむ」をモットーに暮らす二児の母。
- 自分で作ったデジタルプロダクトを公開&アプリストアで出しています。
- 自分で作ったレーベルのプロダクトをネットショップで販売しています。
- 人と対面で会うのとコーヒーが好きなので、子育ての合間に不定期のイベントでコーヒー屋さん（仮）をしています。
- 共著でデザイン本の執筆経験あり。デザインや暮らしにまつわるブログを運営中。

**Comment by torobi** [comment]
以下に盛り込みたい内容をまとめました。
レビューをお願いいたします！

# タイトル
 attsumi profile site

## プロフィール
* プロダクトデザイナー・ディベロッパー・店主
* 「生活を楽しむ」をモットーに暮らす二児の母。
* 自分で作ったプロダクトをネットショップやアプリストアで公開・販売しています。
* 共著でデザイン本の執筆経験あり。デザインや暮らしにまつわるブログを運営中

## プロダクト
- ネットショップへのリンク
- プロダクトへのリンク
- 著書へのリンク

## ブログ
　- ブログの紹介

## 連絡先
Twitter @attsumi

**Comment by taguchi** [comment]
良いと思いますー！レイアウトに進んでください！

**Comment by torobi** [comment]
レビューありがとうございます！
手書きワイヤー程度ではありますが、レイアウトを作成いたしました。
（デザインした状態のがよろしければ差し戻しをお願いします）
ご確認をお願いいたします！
![profilr_after5](https://user-images.githubusercontent.com/6082554/61038947-db73be00-a408-11e9-9c41-e1640e0087e8.png)

**Comment by taguchi** [comment]
これで良いと思います！マークアップに進んでみてください！

**Comment by torobi** [comment]
作成いたしました！ギリギリになってしまい、恐縮ですがレビューをお願いいたします！

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/24ribl3rbdmms2i/307

### うまく出来なかったところ
- 「Product」の３枚画像が並んでいる部分の縦横比率
 - 本当はブラウザサイズを縮小しても画像比率が保たれたままにしたかったのですが、画像の天地中央に文字を入れたかった故に、`line-height`を固定値にして、さらには `background-size : cover`にしているため実現出来ませんでした。

### 悩んだところ
- CSS のクラス名付け。もう少し、他の人にもわかりやすくかつ長くない命名にしたいなと思っております。

**Comment by taguchi** [comment]
そうですね、シンプルでいい感じですが、いくつか。

### 1, 2

`profileItem1`、`profileItem2`みたいなクラス名はあまりよろしくないかもですね。

`profileImage`、`profileDetail`などが良いかな、と思います。

### 画像

> 「Product」の３枚画像が並んでいる部分の縦横比率

これは悩ましいですね。ある程度早い段階（文字が2行になるまえ）に縦並びにしてもいいかも、とは思いました。

ただ、全体的によくできているかと！これでOKかと思います！お疲れ様でした！

**Comment by taguchi** [comment]
Closeしておきます。

**Comment by torobi** [comment]
こちら、ご確認ありがとうございました！

> profileItem1、profileItem2みたいなクラス名はあまりよろしくないかもですね。
> profileImage、profileDetailなどが良いかな、と思います。

確かにですね。。以後気をつけます！
画像の件もありがとうございます。
