### ISSUE TITLE
【基礎練-001】 256の特徴マークアップ

### ISSUE THREAD

**Issue by uchidacode** [torobi/201907-256times#2]
次のプレイグラウンドを複製し、文章を適切なタグでマークアップしてください。

・課題用プレイグラウンド
https://dotinstall.com/pg/taguchi/niecvyhvnzdub00/1

注意点は以下のとおりです。

- HTMLだけ記述してください。CSS、JavaScriptの記述は不要です。
- **文書中で特に重要だと思った箇所については強調のためのタグを使ってマークアップしてください。**
- 提出前に右上メニューから「コードを整形する」を実行してください。

マークアップが終わったら保存して、プレイグラウンドのURLをコメントに貼り付けてください（なお、貼り付ける際は苦労した点や特にレビューしてもらいたい点などについてコメントを添えるといいでしょう）。

**Comment by torobi** [comment]
@uchidacode 
初めまして。torobi と申します。
これからよろしくお願いいたします！
早速ですが、以下に制作物とレビューいただきたい点を記載いたします。

## プレイグラウンドURL
- https://dotinstall.com/pg/torobi/quws3bkx7z1m7gz/9

## 特にレビューしていただきたい点
- 「よく聞かれる質問とその回答」箇所
  - 「質問」をより詳細に説明したものを「回答」と考え、`<dl>` `<dt>` `<dd>` タグでマークアップいたしました。もし適切でない・より好ましい書き方があればご教示いただけると嬉しいです。

## 疑問
- `<p>`タグ について
  -  素朴な疑問ですが、1行などの短い文章の場合、`<span>`との使い分けに迷います。
      -  例えば最下部の`(c) dotinstall.com`は1つの段落であると考え、`<p>`としましたがこちらは適切でしょうか？

**Comment by taguchi** [comment]
おはようございます。コード拝見しました！全体的にきれいなコードですね。

さて何点か...。

### 全体の構成

HTMLのアウトライン（階層）は以下のようなツールで調べることができます。こちらにHTMLを貼り付けてみて、想定しているものになっているか確認できますか...？

https://gsnedders.html5.org/outliner/

### リンク集

```
    <a href="https://dotinstall.com/" target="_blank">ドットインストール</a>
    <a href="https://note.mu/256times" target="_blank">256times公式note</a>
    <a href="https://twitter.com/dotinstall" target="_blank">256times公式ツイッター</a>
```

ですが、（考え方次第ですが）リンクの「一覧」なのでリストでマークアップするのもいいかと思います。

### 空行

コード内に適切な空行をいれると読みやすくなるかと思います。ご検討ください。

---

あとはご質問いただいた件ですね。



> * 「質問」をより詳細に説明したものを「回答」と考え、`<dl>` `<dt>` `<dd>` タグでマークアップいたしました。もし適切でない・より好ましい書き方があればご教示いただけると嬉しいです。

それでバッチリだと思います！



> `<p>`タグ について
> * 素朴な疑問ですが、1行などの短い文章の場合、`<span>`との使い分けに迷います。
>   
>   * 例えば最下部の`(c) dotinstall.com`は1つの段落であると考え、`<p>`としましたがこちらは適切でしょうか？

最後のコピーライトは「行」で表現したいものなので`p`でいいと思います。

なお、`span`は装飾のためのタグなので、文書の意味に応じてマークアップするものではないですね。CSSで「この（インライン的な）箇所についてスタイリングしたい」というときに使います。

---

では、上記の件、修正おわったらコメントしてください！

**Comment by torobi** [comment]
@taguchi 
レビューありがとうございます！
以下、修正いたしました。お手数ですがご確認をお願いします。

###  プレイグラウンドURL
https://dotinstall.com/pg/torobi/quws3bkx7z1m7gz/14

###  修正点
- 「よく聞かれる質問とその回答」箇所
  - ３つの特徴「スパルタ式」「学習＆コミュニティ」「リスクフリー」の見出しレベルを`h3`にしました。
  - 「よく聞かれる質問とその回答」「256timesのロゴについて」「関連リンク集」の見出しレベルを`h3`にしました。
  - 先ほどの提出分では`h2`としていましたが、「256timesの特徴」の見出し`h2`と比較して低いレベルであるべきでは、と考えたからです。
- リンク集
   - リストでマークアップいたしました。
- 空行
  - 空行の度合いについては感覚値にはなりますが、`section`の前後に入れ、コードの可読性を向上しました。

---
疑問やレビューいただきたい点にもご回答ありがとうございます！
`span`はあくまで装飾のためのタグということで理解いたしました。
またアウトラインツールについても教えていただきありがとうございます！

引き続きよろしくお願いいたします。

**Comment by taguchi** [comment]
そうですね・・・。いくつか。



> * 先ほどの提出分では`h2`としていましたが、「256timesの特徴」の見出し`h2`と比較して低いレベルであるべきでは、と考えたからです。

いまのアウトラインを見ると、

<img width="449" alt="スクリーンショット 2019-07-10 0 22 33" src="https://user-images.githubusercontent.com/8720/60901397-d566cb80-a2a8-11e9-884e-baf444bef1c5.png">

となっているので、その考え方はちょっと違いますね。アウトラインレベルでは同等なので、意味的に同列（＝同階層）と考えるべきです。

`h2`にするか`h3`の数値は、あくまでも`section`内での相対的な重要度なので、同じ階層にあるのに「こっちのセクションではなんとなくレベル低そうなので`h3`にしようかな」というのは間違えているような気がします。レベルが低そう、とおもったらアウトラインレベルで階層をさげるべきですね...。

そのあたりの考え方は重要なので再考してみてください。

あと何点か...。

```
    <dl>
      <dt>質問: 256timesで得られるスキルはどの程度のものですか？</dt>
      <dd>回答: 当然ですが、個々人の資質によります。個人的なアドバイスは「とにかく手を動かしてみればいいのでは？」です。256timesのカリキュラムは、ひたすら基礎力の向上に当てられます。そこで得られるものはあくまでも基礎的なスキルですが、コードを書く体験を通じて、「あ、プログラミングってこういう感じか」とわかるようになります。その感覚を得ることができれば、自分の立ち位置や吸収スピードを理解できるので、ある地点に到達するにはどのぐらいの期間が必要かがわかるようになるはずです。</dd>
    </dl>
    <dl>
      <dt>質問: SNSに関するポリシーはありますか？</dt>
      <dd>回答: スクール中に「これはSNSで発言しないでね」と言われたこと以外は自由に発言していただいてかまいません。ただ、発言しなくても全然かまいません。ご自身のポリシーでご判断ください。それよりも大事なのは、他の参加者のプライバシーに十分配慮することです。他のひとについて言及するときは必ず御本人の許可をとりましょう。なお、代表の @taguchi は写真ぎらいなので、スクールで顔写真などを撮影することはありません。最終日の発表会でもイベント写真を撮る予定はありませんし、イベントの参加者にも写真撮影を禁止します。</dd>
    </dl>
    <dl>
      <dt>質問: なぜ無料なのですか？</dt>
      <dd>回答: 受講生にとっても、スクールにとっても、思う存分、試したいことが試せるからです。</dd>
    </dl>
```

ここ、よくみると3つのリストになっていますが、意味的にはひとつのリスト（リストのなかに項目が3つ）なので、`dl`は一つにしましょう。

```
  <section>
    <h3>関連リンク集</h3>
    <ul>
      <li><a href="https://dotinstall.com/" target="_blank">ドットインストール</a></li>
      <li><a href="https://note.mu/256times" target="_blank">256times公式note</a></li>
      <li><a href="https://twitter.com/dotinstall" target="_blank">256times公式ツイッター</a></li>
    </ul>
    <footer>
      <p>
        (c) dotinstall.com
      </p>
    </footer>
  </section>
```

こう書いてしまうと、「(c) dotinstall.com」は「関連リンク集」セクションのフッター、という意味になりますね。そうではなくてページ全体のcopyrightかと思うので位置を再考してください。

---

以上、見直してみてください！

**Comment by torobi** [comment]
@taguchi 
レビューありがとうございます！
再考、修正いたしましたのでご確認をお願いいたします。

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/quws3bkx7z1m7gz/16

### 修正点
- 「質問・回答」のリスト調整
- footer の位置調整
  - 「関連リンク集」のセクションから外に出しました。
-  「よく聞かれる質問とその回答」「256timesのロゴについて」「関連リンク集」の見出しレベルを`h2`に

`h2にするかh3の数値は、あくまでもsection内での相対的な重要度なので`
ご教示ありがとうございます。理解いたしました。

**Comment by taguchi** [comment]
そうですね、だいぶ良いですね。

あとは、

```
<h1>256timesについて</h1>
```

は`header`で囲ってもいいかな、というのと`h3`も`section`で囲うとなおよいかと思います。

ご検討ください。

**Comment by torobi** [comment]
レビューありがとうございます！

>`header`で囲ってもいいかな
> `h3`も`section`で囲うとなおよい

確かにそうですね...！上記修正しました。
お手数ですが、再度ご確認をお願いいたします。

### プレイグランドURL
https://dotinstall.com/pg/torobi/quws3bkx7z1m7gz/17

**Comment by taguchi** [comment]
とても良いと思います！こちらはCloseしておきます。お疲れ様でした。
他の課題がんばってみてください！
