### ISSUE TITLE
【基礎練-002】 要素の配置

### ISSUE THREAD

**Issue by uchidacode** [torobi/201907-256times#3]
次のプレイグラウンドを複製し、以下の画像のようなレイアウトを制作してください。

・課題用プレイグラウンド
https://dotinstall.com/pg/taguchi/7tcwisbovy9ht18/1

注意点は以下のとおりです。

- HTML/CSSだけ記述してください。JavaScriptの記述は不要です。
- 色は上から`pink`、`tomato`、`gold`、`skyblue`を使うといいです。
- `gold`と`skyblue`の領域の幅は400pxです。
- 領域と領域のあいだの（縦の）余白は15pxです。
- それぞれの領域の高さは120pxです。
- 提出前に右上メニューから「コードを整形する」を実行してください。

マークアップが終わったら保存して、プレイグラウンドのURLをコメントに貼り付けてください（なお、貼り付ける際は苦労した点や特にレビューしてもらいたい点などについてコメントを添えるといいでしょう）。

![01](https://user-images.githubusercontent.com/19469896/60768433-d956ea00-a0fe-11e9-9f90-3db6c9793de0.gif)

**Comment by torobi** [comment]
課題を作成しました。
ご確認をお願いいたします！

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/d9ivnfozammh5i2/10

**Comment by taguchi** [comment]
良いですね。何点か。

```
.box {
  height: 120px;
  line-height: 120px;
  margin-bottom: 15px;
}
```

↑ すべてのプロパティが必要ですか...？

```
.pink {
  text-align: left;
  background-color: pink;
}
```

↑ こちらもすべて必要ですか？

あと、お手本の画像をみるとピンクの領域の左右や上に余白がないのがわかります。そのようなスタイルをつけてみてください。

---

以上、ご確認ください！

**Comment by torobi** [comment]
レビューいただきありがとうございます！
以下、修正いたしました。お手数ですがご確認をお願いいたします。

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/hf23z4gdqs4ybcc/7

### 修正点
- ピンク領域の左右・上の余白削除
- `.box` `.pink` 不要なプロパティ削除

---
今回の`.box` の`height`  `line-height`に関して、ご指摘を受けて、確かに・・となりました。
今までも同様の表現をする際に両方書いてきたので、今後は改めます。

また、プロパティの初期値をあまり意識せずでいましたが、今後は意識して、
不要なコードを記載しないように心がけていきます。
(`text-align`の初期値は`start`で今回の場合は`left`と同義なので不要)

**Comment by taguchi** [comment]
良いと思います。Closeで！
