### ISSUE TITLE
【基礎練-003】 要素の配置（Flexbox）

### ISSUE THREAD

**Issue by uchidacode** [torobi/201907-256times#4]
次のプレイグラウンドを複製し、以下の画像のようなレイアウトを制作してください。

・課題用プレイグラウンド
https://dotinstall.com/pg/taguchi/7tcwisbovy9ht18/1

注意点は以下のとおりです。

- HTML/CSSだけ記述してください。JavaScriptの記述は不要です。
- 色は`pink`、`skyblue`、`gold`を使うといいです。
- `*-1`、`*-3`の幅は100pxです。
- `1-2`の幅は200pxです。
- `4-1`、`4-2`、`4-3`の間の（横の）余白は10pxです。
- 領域と領域のあいだの（縦の）余白は15pxです。
- それぞれの領域の高さは120pxです。
- flexboxを使って実装してください。
- 提出前に右上メニューから「コードを整形する」を実行してください。

マークアップが終わったら保存して、プレイグラウンドのURLをコメントに貼り付けてください（なお、貼り付ける際は苦労した点や特にレビューしてもらいたい点などについてコメントを添えるといいでしょう）。

![02](https://user-images.githubusercontent.com/19469896/60768480-626e2100-a0ff-11e9-9409-385fe3486fe2.gif)

**Comment by torobi** [comment]
作成いたしました。ご確認よろしくお願いいたします！

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/nnubocfnw3xegw5/36

### 悩んだ点
- 各flexアイテムへのCSSクラスの振り方
  - できるだけ共通化できるものはまとめたつもりですが、まとめるまでに少し悩みました。

**Comment by taguchi** [comment]
そうですね・・・。`calc`でもいいですが、せっかくflexboxをつかったので「flexbox margin」などで調べてみるといいかもしれません。

それからプレイグラウンドの右側をぐっと狭くすると1-1が100px以下になってしまいます。そのあたりも直せますか？

※ ただ、プロフィールサイトを優先させたほうがいいかとは思います。

**Comment by torobi** [comment]
レビューありがとうございます！
修正いたしました。
お手数ですが、ご確認のほど、よろしくお願いいたします。

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/nnubocfnw3xegw5/41

### 修正点
- `calc` を削除し、`flex : 1` を追加
- `1-1` に `min-width:100px`を追加

**Comment by taguchi** [comment]
よいと思います！Closeしておきます。
