### ISSUE TITLE
【基礎練-004】 要素の配置（Flexbox応用編）

### ISSUE THREAD

**Issue by uchidacode** [torobi/201907-256times#5]
次のプレイグラウンドを複製し、以下の画像のようなレイアウトを制作してください。

・課題用プレイグラウンド
https://dotinstall.com/pg/taguchi/7tcwisbovy9ht18/1

注意点は以下のとおりです。

- HTML/CSSだけ記述してください。JavaScriptの記述は不要です。
- 色は`pink`、`skyblue`、`gold`を使うといいです。
- `1-2`の幅は200px、それ以外の要素の幅は100pxです。
- `3-1`の左端から`3-3`の右端までは400pxです。
- 領域と領域のあいだの（縦の）余白は15pxです。
- それぞれの領域の高さは120pxです。
- flexboxを使って実装してください。
- 提出前に右上メニューから「コードを整形する」を実行してください。

マークアップが終わったら保存して、プレイグラウンドのURLをコメントに貼り付けてください（なお、貼り付ける際は苦労した点や特にレビューしてもらいたい点などについてコメントを添えるといいでしょう）。

![03](https://user-images.githubusercontent.com/19469896/60768521-ee804880-a0ff-11e9-9d78-de69252a2b74.gif)

**Comment by torobi** [comment]
課題を作成しました。
レビューをお願いいたします。

### プレイグラウンド
https://dotinstall.com/pg/torobi/qlt0h7504c27xvm/64

### ご質問
- 'margin-left:auto' について
 - 今回、右寄せにするボックスに 'margin-left:auto' をつけました。
   - この記事を参照しています
     - https://coliss.com/articles/build-websites/operation/css/css-flexbox-and-auto-margins.html
 - 初めてこのような形で使用したため、理解が合っているのか確認できると嬉しいのですが「'margin-left'が取りうることができる一番最大の領域まで取る、かつ可変」という理解であっていますでしょうか・・？

**Comment by taguchi** [comment]
> * 初めてこのような形で使用したため、理解が合っているのか確認できると嬉しいのですが「'margin-left'が取りうることができる一番最大の領域まで取る、かつ可変」という理解であっていますでしょうか・・？

そうですね、その理解でOKです！あとひとつ加えるなら`margin-right: auto`も同時に指定したら余白を均等に分配する、といった感じですかね。

課題はOKそうだったのでCloseしておきます。

**Comment by torobi** [comment]
ご回答いただき、ありがとうございます！

>その理解でOKです！
>あとひとつ加えるならmargin-right: autoも同時に指定したら余白を均等に分配する、といった感じですかね。
なるほどです....！
`margin: 0 auto;`の意味が腹落ちいたしました。。
ありがとうございます！

**Comment by torobi** [comment]
課題はOKそうとのことですので、Closeします（問題あればOpen お願いいたします）

**Comment by taguchi** [comment]
Closeし忘れていました！Closeで良いです！
