### ISSUE TITLE
【基礎練-005】 グリッド配置（Flexbox）

### ISSUE THREAD

**Issue by uchidacode** [torobi/201907-256times#6]
次のプレイグラウンドを複製し、以下の画像のようなレイアウトを制作してください。

・課題用プレイグラウンド
https://dotinstall.com/pg/taguchi/7tcwisbovy9ht18/1

注意点は以下のとおりです。

- HTML/CSSだけ記述してください。JavaScriptの記述は不要です。
- 色は`pink`、`tomato`、`gold`、`skyblue`、`lime`を使うといいです。
- それぞれの領域の幅、高さは100pxです。
- 領域の上部にある余白は15pxです。
- flexboxを使って実装してください。
- 提出前に右上メニューから「コードを整形する」を実行してください。

マークアップが終わったら保存して、プレイグラウンドのURLをコメントに貼り付けてください（なお、貼り付ける際は苦労した点や特にレビューしてもらいたい点などについてコメントを添えるといいでしょう）。

<img width="549" alt="04" src="https://user-images.githubusercontent.com/19469896/60768774-c6deaf80-a102-11e9-8388-91df5fa31599.png">

**Comment by torobi** [comment]
本課題、作成いたしました。
お手数ですが、レビューのほどよろしくお願いいたします！

## プレイグラウンドURL
https://dotinstall.com/pg/torobi/s0gj93mk1t7a39i/4

## 特にレビューしてもらいたい点
- 各数字をそれぞれのボックスに対して天地中央にする方法
 - `line-height` を親要素の高さに合わせています。少しハック的なやり方だとは思うのですが、もし問題ある場合にはご指摘いただけますと幸いです。

**Comment by torobi** [comment]
7/10 22:40：1つ前のコメントで、プレイグラウンドURLを修正いたしました。

**Comment by taguchi** [comment]
そうですね・・・。挙動としてはOKですが、効きそうなプロパティをとりあえずつけておこう、的な感じになっているのが気になります。

```
body {
  width: 300px;
  margin: 15px auto 0;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: left;
  flex-wrap: wrap;
}

.box {
  width: 100px;
  line-height: 100px;
  text-align: center;
  vertical-align: middle;
}
```

のなかになくてもいいプロパティがいくつかありますがわかりますか？

**Comment by taguchi** [comment]
> * `line-height` を親要素の高さに合わせています。少しハック的なやり方だとは思うのですが、もし問題ある場合にはご指摘いただけますと幸いです。

これはこれでいいと思います。親要素にあわせる、というよりも`line-height`をつかって行ボックスの高さを指定している、ということですね。

https://dotinstall.com/lessons/basic_css_styles/45409

も見直してみるといいですね。

**Comment by torobi** [comment]
フィードバックありがとうございます！
以下、調整いたしました。お手数ですがご確認をお願いいたします。

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/s0gj93mk1t7a39i/17

###  修正点
- 不要プロパティの削除
  - ` justify-content: left;`, `vertical-align: middle;`を削除しました。

---
疑問点に関しても回答ありがとうございます！
ご教示いただいたドットインストールURL見直しました。

**Comment by taguchi** [comment]
そうですね、考え方としてはいいのですが、`body`に直接`width`などをつけるのはあまりよろしくないかもですね（その他の要素をそのあとに追加できなくなったりする）。今回はきちんと`div`で囲ってスタイリングしてみましょう。

**Comment by torobi** [comment]
>bodyに直接widthなどをつけるのはあまりよろしくないかもですね（その他の要素をそのあとに追加できなくなったりする）

確かにですね。。修正いたします！

**Comment by torobi** [comment]
上記修正いたしました。
度々恐縮ですが、ご確認をお願いいたします！

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/s0gj93mk1t7a39i/18

**Comment by taguchi** [comment]
良いと思います！

こちらはCloseで。
