### ISSUE TITLE
【基礎練-006】 グリッド配置（応用編）

### ISSUE THREAD

**Issue by uchidacode** [torobi/201907-256times#7]
次のプレイグラウンドを複製し、以下の画像のようなレイアウトを制作してください。

・課題用プレイグラウンド
https://dotinstall.com/pg/taguchi/7tcwisbovy9ht18/1

注意点は以下のとおりです。

- HTML/CSSだけ記述してください。JavaScriptの記述は不要です。
- 色は`pink`、`tomato`、`gold`、`skyblue`、`lime`を使うといいです。
- それぞれの領域の幅、高さは100pxです。
- 領域の上部にある余白は15pxです。
- グリッドの間にある余白は縦横それぞれ15pxです。
- 提出前に右上メニューから「コードを整形する」を実行してください。

マークアップが終わったら保存して、プレイグラウンドのURLをコメントに貼り付けてください（なお、貼り付ける際は苦労した点や特にレビューしてもらいたい点などについてコメントを添えるといいでしょう）。

<img width="555" alt="05" src="https://user-images.githubusercontent.com/19469896/60768776-c7774600-a102-11e9-819f-4aeb9fa58483.png">

**Comment by torobi** [comment]
課題を作成しました。
レビューのほど、よろしくお願いいたします！

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/277wqb1por9ls01/43

**Comment by taguchi** [comment]
そうですね・・・・。

- できればcontainerは1つで実装したいところです。
- 最後の要素に`left`をつけるのはちょっと力技かもです。

なお、この課題には「flexboxを使いましょう」とは言われていないので、違う技術を使ってもOKです。

**Comment by torobi** [comment]
フィードバックありがとうございます！
以下、修正いたしました。度々お手数ですがご確認をお願いします。

### プレイグラウンドURL
https://dotinstall.com/pg/torobi/277wqb1por9ls01/51

### 修正点
- `display: grid` を使用し、`gap`で余白を作成。

**Comment by taguchi** [comment]
```
.left{
  margin-left: 15px;
  margin-right: auto;
}
```

は不要ですね。

あとはOKです！Closeしておきます。

**Comment by torobi** [comment]
不要クラスが混じっており、失礼しました...！
ご確認ありがとうございます。
