### ISSUE TITLE
【基礎練-007】 名刺デザイン

### ISSUE THREAD

**Issue by uchidacode** [torobi/201907-256times#8]
次のプレイグラウンドを複製し、以下の注意点にしたがってマークアップしてください。

・課題用プレイグラウンド
https://dotinstall.com/pg/taguchi/saqzpghhecsy8k3/1

注意点は以下のとおりです。

- HTML/CSSだけ記述してください。JavaScriptの記述は不要です。
- HTML内に記述された内容をもとに名刺をデザインしてください。
  - ご自身がもっとも美しいと思える配置、スタイルにしてください。
- `.card`の`width`と`height`を変更してはいけません。
- レイアウトに関してはCSSの絶対配置などを使うと良いでしょう。
- ロゴ画像は以下のどちらかを使ってください。
  - https://dotinstall.com/img/256times/logo-h.svg
  - https://dotinstall.com/img/256times/logo-v.svg
- Google Fontsを使ってもOKです。
- 提出前に右上メニューから「コードを整形する」を実行してください。

マークアップが終わったら保存して、プレイグラウンドのURLをコメントに貼り付けてください（なお、貼り付ける際は苦労した点や特にレビューしてもらいたい点などについてコメントを添えるといいでしょう）。

**Comment by torobi** [comment]
マークアップいたしました。
ご確認のほど、よろしくお願いいたします！

### プレイグラウンド URL
https://dotinstall.com/pg/torobi/adcd0btn14c8rtd/171

### 難しかったところ
- ロゴと余白のバランスを取るのが難しかったです....

**Comment by taguchi** [comment]
きれいな仕上がりでいいかと思います！

連絡先は`address`タグでもいいかな、と思ったぐらいですね。文字色を変えて情報の重要度を表現していて素晴らしいと思いました！

こちらはCloseしておきます！

**Comment by torobi** [comment]
レビューありがとうございます！

>連絡先はaddressタグでもいいかな
なるほどです・・・！勉強になります。
今後の参考にさせていただきます！
